#!/usr/bin/env node

let https = require('follow-redirects').https;
let unzip = require('unzip-stream');
let concat = require('concat-stream')
let xml2js = require('xml2js');
let fs = require('fs');

const OUTPUT_DIR = __dirname + '/../www/i18n/';

https.get('https://crowdin.com/download/project/lichess.zip', function (response) {
  response.pipe(unzip.Parse())
  .on('entry', function (entry) {
    if (entry.type === 'File' && entry.path.startsWith('master/translation/dest/site/')) {
      let lang = entry.path.substr(29, 2);
      entry.pipe(concat(function (buffer) {
        xml2js.parseString(buffer.toString('utf-8'), function(err, result) {
          if (!err) {
            json = {};
            if (result.resources.string) {
              for (let tr of result.resources.string) {
                json[tr.$.name] = tr._;
              }
            }
            if (result.resources.plurals) {
              for (let tr of result.resources.plurals) {
                plural = {};
                for (let item of tr.item) {
                  plural[item.$.quantity] = item._;
                }
                json[tr.$.name] = plural;
              }
            }
            fs.writeFileSync(OUTPUT_DIR + lang + '.json', JSON.stringify(json));
          }
        });
      }))
    } else {
      entry.autodrain();
    }
  })
}).on('error', function (err) {
  console.error(err);
});

